### ISSUE TITLE
master_run.py failed with missing handcar_cosim.so

### ISSUE THREAD

**Issue by guoheng** [openhwgroup/force-riscv#2] opened 2020-06-13 15:52 UTC
Build successfully. When run master_run.py, failed with the message below:
FileNotFoundError: Path resolution for [--fpix_riscv.iss_so_path] failed, [/home/guoheng/force-riscv/utils/handcar/handcar_cosim.so] could not be located

What's the instruction of get the handcar_cosim.so?

**Comment by Leo-Wang-JL** [comment] 2020-06-13 22:09
Thank you for reporting this Issue!

The handcar_cosim.so was intended to be included in the initial commit but it was omitted unintentionally due to a .gitignore file.

The handcar_cosim.so can be also build from the code in the handcar directory.  How every we found that there are some files missing in that directory as well.  We will get that addresses ASAP so that you can confidently build the handcar_cosim.so yourself.

**Comment by Leo-Wang-JL** [comment] 2020-06-14 01:29
The missing SO file has been committed to the master branch.  Please try it out.

**Comment by Leo-Wang-JL** [comment] 2020-06-14 05:20
Submitted a pull request:
"Updated README.md to describe how to build handcar_cosim.so. Updated script in handcar/regenerate_and_build.bash that can be used to build handcar_cosim.so"

**Closed** 2020-06-24 14:16 UTC
