### ISSUE TITLE
generated test examples

### ISSUE THREAD

**Issue by agrobman** [openhwgroup/force-riscv#25] opened 2020-12-13 22:30 UTC
Hi, 

Could you, guys provide the generated tests *.s files for every python template?

It will greatly help to assess the tool capability...

thanks in advance

**Comment by noahsherrill** [comment] 2021-01-04 16:01
You can build and run FORCE by following the instructions here: https://github.com/openhwgroup/force-riscv#setup. Add `-k all` to the command for running the FORCE regression in order to retain the .S files for each test run, so the command to run the tests looks like `./utils/regression/master_run.py -k all`. Then, the .S files will be located in the subdirectories in `output/regression`.

**Comment by noahsherrill** [comment] 2021-01-11 16:33
@agrobman, do you have any further questions? If not, I will suggest this issue be closed.

**Comment by noahsherrill** [comment] 2021-01-15 18:22
@MikeOpenHWGroup, I suggest this issue be closed. The question was answered, and no follow-up questions were posted.

**Comment by hanfeng0114** [comment] 2023-05-06 01:28
@MikeOpenHWGroup please help to close this issue.

**Closed** 2023-05-06 17:13 UTC
