### ISSUE TITLE
"action_code_reg_val" was pushed into DataBlock twice 

### ISSUE THREAD

**Issue by niuqiang-real** [openhwgroup/force-riscv#48] opened 2022-02-24 02:03 UTC
Hi there,

   Please check whether this part of code in GenExceptionAgentRISCV.cc is correct or not:
 
![image](https://user-images.githubusercontent.com/99661322/155443206-54681bd0-e94b-486e-920e-40af6c37d951.png)

Here, I think there are two mistakes:

    The first one is at Line 271: data pushed into data block should be data_block_addr_reg_val;
    The second one is at Line 269: it should be "action_code_reg_val" instead of "result.mTargetAddr".

And why do we put current address of the AddressTable into data block? I don't really understand what AddressTable is used for. I would appreciate it if you can help me.

**Comment by noahsherrill** [comment] 2022-03-01 17:46
Thank you for your careful review of the code. The code is definitely incorrect, but was not causing any unexpected behavior. I took a closer look to determine why, and it turns out that adding the action code, data block address and an address from the address table to the data block was completely unnecessary. The action code and data block address are returned through the API, and the address table address wasn't needed at all. I will submit a fix for this soon.

The main purpose of the address table is to provide recovery addresses for some of the exception handlers to use. Some of the fast exception handlers jump to a safe location to continue execution. The address table provides a list of known valid addresses that the exception handlers can jump to. You can see `py/riscv/exception_handlers/FastExceptionHandlers.py` for an example of how the address table is used.

**Closed** 2022-03-01 18:55 UTC
